#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com

ADMIN='gert:passwd'
DB='www/_design'
REV=`curl -sIX HEAD http://$ADMIN@localhost:5984/$DB/${1%%/*}`
MIME=`file -ib $1`
if [[ $REV =~ Etag:\ \"(.*)\" ]]; then
 curl -X PUT http://$ADMIN@localhost:5984/$DB/$1?rev=${BASH_REMATCH[1]} -H "Content-Type: ${MIME%%;*}" --data-binary @$1
 else
 curl -X PUT http://$ADMIN@localhost:5984/$DB/$1 -H "Content-Type: ${MIME%%;*}" --data-binary @$1
fi

