#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com

ADMIN='gert:passwd'
TYPE=${1#*.}
DOC=${1%/*}
MIME='application/json'
#MIME=`file -ib $1`
case $TYPE in
 htm) MIME='text/html';;
 css) MIME='text/css';;
 js)  MIME='text/javascript';;
 png) MIME='image/png';;
 ico) MIME='image/x-icon';;
 ogg) MIME='audio/ogg';;
 webm)MIME='video/webm';;
 *)   DOC=${1%.*};;
esac

HEAD=`curl -sIX HEAD http://$ADMIN@localhost:5984/$DOC`
if [[ $HEAD =~ ETag:\ \"(.*)\" ]]; then
 REV=${BASH_REMATCH[1]}
fi

if [ $MIME != 'application/json' ]; then
 DOC=$1
fi

curl -X PUT http://$ADMIN@localhost:5984/$DOC \
 -H 'If-Match: '$REV \
 -H 'Content-Type: '${MIME%%;*} \
 --data-binary @$1

