#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com

ADMIN='gert:passwd'
HEAD=`curl -sIX HEAD http://$ADMIN@localhost:5984/$1`
MIME=`file -ib $1`
MIME='application/json'
if [[ $HEAD =~ Etag:\ \"(.*)\" ]]; then
 curl -X PUT http://$ADMIN@localhost:5984/$1 \
 -H 'If-Match: '${BASH_REMATCH[1]} \
 -H 'Content-Type: '${MIME%%;*} \
 --data-binary @$1
 else
 curl -X PUT http://$ADMIN@localhost:5984/$1 \
 -H 'Content-Type: '${MIME%%;*} \
 --data-binary @$1
fi
