#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com
./put users
./put users/_security
./put users/_design/users
./put www/_security
./put www/_design/www
./put www/htm/users.htm
./put www/css/users.css
./put www/png/users.png
./put www/js/http.js
