#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com
./put _users
./put _users/_security
./user gert passwd \"admin\"
./user user passwd
./put www
./put www/_security
./put www/lib/http.js
./put www/user/user.htm
./put www/user/user.css
./put www/user/user.png
./put users
./put users/_design/user

