#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com
./put _users
./put _users/_security
./user gert passwd \"admin\"
./user user passwd
./put users
./put users/_security
./put users/_design/user.db
./put users/_design/user/user.htm
./put users/_design/user/user.css
./put users/_design/user/user.png
./put users/_design/user/http.js

