#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com
ADMIN1='couchdb:passwd'
ADMIN2='couchdb:passwd'
curl -X POST http://$ADMIN1@localhost:5984/_replicate -H'Content-Type: application/json' -d'{
 "source":"users",
 "target":"http://'$ADMIN2'@gert.iriscouch.com/users",
 "filter":"user/design",
 "continuous":false
}'
echo
curl -X GET  http://$ADMIN1@localhost:5984/_active_tasks
#curl -X POST http://$ADMIN1@localhost:5984/_replicate -H'Content-Type: application/json' -d'{
# "replication_id":"'$1'",
# "cancel":true
#}'
