#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com
ADMIN='couchdb:passwd'
curl -X POST http://$ADMIN@localhost:5984/_replicator -H'Content-Type: application/json' -d'{
 "source":"users",
 "target":"gert",
 "continuous":false,
 "filter":"users/www",
 "user_ctx":{
  "name": "couchdb",
  "roles": ["_admin"]
 }
}'
echo

#curl -X GET  http://$ADMIN1@localhost:5984/_active_tasks
#curl -X POST http://$ADMIN1@localhost:5984/_replicate -H'Content-Type: application/json' -d'{
# "replication_id":"'$1'",
# "cancel":true
#}'

# "target":"http://'$ADMIN'@localhost:5984/users",
# "doc_ids":["_design/users"],
