#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com

ADMIN='gert:passwd'
SALT=`openssl rand 16 | openssl md5`
SHA1=`echo -n $2$SALT | openssl sha1`
HEAD=`curl -sIX HEAD http://$ADMIN@localhost:5984/_users/user%3A$1`
#echo ${HEAD%%$'\n'*}

if [[ $HEAD =~ Etag:\ \"(.*)\" ]]; then
 REV='"_rev":"'${BASH_REMATCH[1]}'",'
fi

curl -X PUT http://$ADMIN@localhost:5984/_users/user%3A$1 -H 'Content-Type: application/json' -d'{
  "_id"          : "user:'$1'",
  '$REV'
  "type"         : "user",
  "name"         : "'$1'",
  "roles"        : [],
  "password_sha" : "'$SHA1'",
  "salt"         : "'$SALT'"
}'

<<TODO
curl -X GET http://$ADMIN@localhost:5984/_session
curl -X DELETE http://$ADMIN@localhost:5984/_session
curl -X PUT http://$ADMIN@localhost:5984/db/_security -H 'Content-Type: application/json' -d'{
  "admins" : {
     "names" : [],
     "roles" : []
   },
   "readers" : {
     "names" : [],
     "roles" : []
   }
}'
TODO
