#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com

ADMIN='couchdb:passwd'
SALT=`openssl rand 16 | openssl md5`
SHA1=`echo -n $2$SALT | openssl sha1`
HEAD=`curl -sI http://$ADMIN@localhost:5984/_users/org.couchdb.user%3A$1`
#echo ${HEAD%%$'\n'*}
if [[ $HEAD =~ ETag:\ \"(.*)\" ]]; then
 REV=${BASH_REMATCH[1]}
fi

curl -X PUT http://$ADMIN@localhost:5984/_users/org.couchdb.user%3A$1 \
-H 'If-Match: '$REV \
-H 'Content-Type: application/json' \
-d '{
 "type"         : "user",
 "name"         : "'$1'",
 "roles"        : ['$3'],
 "password_sha" : "'$SHA1'",
 "salt"         : "'$SALT'"
}'

#curl -X GET http://$ADMIN@localhost:5984/_session
#curl -X DELETE http://$ADMIN@localhost:5984/_session
