#!/bin/bash
# Copyright(c) gert.cuykens@gmail.com

ADMIN='gert:passwd'
DB='www'
DOMAIN='org.couchdb.user'
SALT=`openssl rand 16 | openssl md5`
SHA1=`echo -n $2$SALT | openssl sha1`
REV=`curl -sIX HEAD http://$ADMIN@localhost:5984/_users/$DOMAIN%3A$1`

if [[ $REV =~ Etag:\ \"(.*)\" ]]; then
 echo DELETE http://$ADMIN@localhost:5984/_users/$DOMAIN%3A$1?rev=${BASH_REMATCH[1]}
 curl -X DELETE http://$ADMIN@localhost:5984/_users/$DOMAIN%3A$1?rev=${BASH_REMATCH[1]}
else
 echo ${REV%%$'\n'*}
fi

echo PUT http://$ADMIN@localhost:5984/_users/$DOMAIN%3A$1
curl -X PUT http://$ADMIN@localhost:5984/_users/$DOMAIN%3A$1 -H 'Content-Type: application/json' -d'{
  "_id"          : "'$DOMAIN:$1'",
  "type"         : "user",
  "name"         : "'$1'",
  "roles"        : [],
  "password_sha" : "'$SHA1'",
  "salt"         : "'$SALT'"
}'

echo PUT http://$ADMIN@localhost:5984/$DB/_security
curl -X PUT http://$ADMIN@localhost:5984/$DB/_security -H 'Content-Type: application/json' -d'{
  "admins" : {
     "names" : [],
     "roles" : []
   },
   "readers" : {
     "names" : [],
     "roles" : []
   }
}'

#curl -X GET http://$ADMIN@localhost:5984/_session
#curl -X DELETE http://$ADMIN@localhost:5984/_session

